
language: elixir

sudo: required

elixir:
  - 1.6.0
  - 1.6.6
  - 1.7.0
  - 1.7.1
  - 1.7.2
  - 1.7.3
  - 1.7.4
otp_release:
  - 19.3
  - 20.2
  - 21.0

services:
- docker

matrix:
  exclude:
    - elixir: 1.6.0
      otp_release: 21.0

env:
  - MIX_ENV=test

install:
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get
  - docker pull rabbitmq:management
  - docker pull hello-world:latest

script:
  - if [[ $(elixir --version) = *"1.7"* ]]; then mix format --check-formatted; fi
  - mix compile
  - mix test
